### PR TITLE
Fixed a minor bug while installation

### LINKED ISSUE #206: More Installation Errors on Raspbian Scratch
**Describe the bug**
Installation Errors on Raspberry Pi Zero W

**To Reproduce**
1. Flash a new version of raspbian to raspberry pi
2. Clone susi_linux repo
3. Run install.sh

**Expected behavior**
A smooth installation without errors

**Screenshots**

- Original Log
[Terminal Log (Pastebin)](https://pastebin.com/GdWWNHBh)
- After #212 
[Terminal Log (Pastebin)](https://pastebin.com/SzixK752)
- After Meeting on 03/07/18
[Terminal Log (Pastebin)](https://pastebin.com/3hF0VQBd)
- Install Attempt on 06/07/18
[Terminal Log (Pastebin)](https://pastebin.com/TuK6aHYJ)

**Additional context**
A different error occurs on ubuntu 18.04 LTS (#208 )

### PR DESCRIPTION
**Pull request by stealthanthrax**
Fixes #206 

Changes
This fixes the bug which was not allowing the installation of dependent libraries if there was some issue in Server build

### CODE REVIEW

**Comment by stealthanthrax** [comment]
@prateekiiest @codesun , please have a look too

File: install.sh [hunk 1]
```diff
@@ -121,31 +120,30 @@ function install_snowboy()
...
-        ./gradlew build 
-    } || {
-        echo PASS
-    }
-
-    bin/start.sh
-fi
+function susi_server(){
+    if  [ ! -d "susi_server" ]
+    then
```
Comment (prateekiiest) [inline install.sh]: looks good since you have made it as a function
